version: '3'

# Operations commands
# Environment utilities

tasks:
  env:print:
    desc: "Print all environment variables"
    cmds:
      - node ../../../automation/scripts/env.mjs print
    silent: false

  env:status:
    desc: "Show environment status with service info"
    cmds:
      - node ../../../automation/scripts/env.mjs status
    silent: false

  env:switch:
    desc: "Switch environment mode (future implementation)"
    cmds:
      - echo "🔄 Environment switching not yet implemented"
      - echo "   This will support - Local/Worktree/Staging modes"
    silent: false

