version: '3'

# Backend database management
# Encore maintains separate database clusters for dev (encore run) and test (encore test)

tasks:
  # Dev cluster commands (for encore run)
  db:migrate:
    desc: "Run migrations on dev cluster"
    cmds:
      - echo "🔄 Running migrations on dev cluster..."
      - cd ../../../backend && encore db migrate
      - echo "✅ Dev cluster migrations complete"
    silent: false

  db:reset:
    desc: "Reset dev cluster database (DESTRUCTIVE)"
    prompt: "This will delete all DEV data. Continue?"
    cmds:
      - echo "⚠️  Resetting dev cluster database..."
      - cd ../../../backend && encore db reset --all
      - echo "✅ Dev cluster database reset"
    silent: false

  db:shell:
    desc: "Open dev cluster database shell. To be used along side encore run."
    cmds:
      - echo "🗄️  Opening dev cluster shell..."
      - cd ../../../backend && encore db shell db --write
    silent: false

  # Test cluster commands (for encore test)
  db:migrate:test:
    desc: "Run migrations on test cluster"
    cmds:
      - echo "🔄 Running migrations on test cluster..."
      - cd ../../../backend && encore db migrate --test
      - echo "✅ Test cluster migrations complete"
    silent: false

  db:reset:test:
    desc: "Reset test cluster database (DESTRUCTIVE)"
    cmds:
      - echo "⚠️  Resetting test cluster database..."
      - cd ../../../backend && encore db reset --all --test
      - echo "✅ Test cluster database reset"
    silent: false

  db:shell:test:
    desc: "Open test cluster database shell. To be used when debugging backend tests."
    cmds:
      - echo "🗄️  Opening test cluster shell..."
      - cd ../../../backend && encore db shell db --test --write
    silent: false

  # Utility commands
  db:status:
    desc: "Show database connection info for both clusters"
    cmds:
      - echo "📊 Database Status"
      - echo ""
      - echo "Dev Cluster (encore run):"
      - cd ../../../backend && encore db conn-uri db 2>&1 || echo "  ⚠️  Dev cluster not available"
      - echo ""
      - echo "Test Cluster (encore test):"
      - cd ../../../backend && encore db conn-uri db --test 2>&1 || echo "  ⚠️  Test cluster not available"
    silent: false
